name: CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    env:
      CI: true

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          check-latest: true

      - name: Install system deps (jq, Podman)
        run: |
          sudo apt-get update
          sudo apt-get install -y jq podman

      - name: Create .env.test from secret
        run: |
          printf "%s" "${{ secrets.ENV_TEST }}" > .env.test

      - name: Make test.sh executable
        run: chmod +x ./test.sh

      - name: Cache npm backend
        uses: actions/cache@v4
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('backend/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Cache npm frontend
        uses: actions/cache@v4
        with:
          path: |
            frontend/node_modules
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('frontend/package-lock.json', 'package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Run full test suite
        run: ./test.sh

      - name: Upload error logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: |
            frontend/playwright-report
            playwright-report
          if-no-files-found: ignore
